import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { SessionProvider } from "next-auth/react";
import { use } from "react";
import { ThemeProvider } from "@/components/theme-provider";
import UserProfile from "@/components/UserProfile";
import { auth } from "@/lib/auth";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = use(auth());

  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-5 antialiased`}
      >
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <nav className="flex h-16 items-center border-b px-6">
              <div className="text-xl font-semibold">TechLog</div>
              <div className="ml-auto flex items-center gap-4">
                {session?.user ? (
                  <>
                    <span className="text-sm">{session.user.name}</span>
                    <UserProfile data={session} />
                  </>
                ) : (
                  <Link href="/sign" className="text-sm">
                    sign
                  </Link>
                )}
              </div>
            </nav>
            <div className="border p-3">{children}</div>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
