import { Search } from "lucide-react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import { SessionProvider } from "next-auth/react";
import { use } from "react";
import UserProfile from "@/components/sign/UserProfile";
import { ThemeProvider } from "@/components/theme-provider";
import { auth } from "@/lib/auth";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = use(auth());

  return (
    <html lang="ko" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} mx-5 antialiased`}
      >
        <SessionProvider session={session}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <nav className="flex h-16 items-center border-b px-6">
              <Link href="/" className="text-xl font-semibold hover:opacity-80">
                TechLog
              </Link>

              <div className="ml-auto flex items-center gap-4">
                {session?.user?.isadmin && (
                  <>
                    <Link href="/admin" className="text-sm font-medium">
                      회원관리
                    </Link>
                    <Link
                      href="/write"
                      className="rounded-full border px-4 py-2 text-sm font-medium"
                    >
                      새 글 작성
                    </Link>
                  </>
                )}

                <button
                  type="button"
                  aria-label="search"
                  className="rounded-full p-2 hover:bg-muted"
                >
                  <Search className="h-5 w-5" />
                </button>

                {session?.user ? (
                  <UserProfile data={session} />
                ) : (
                  <Link href="/sign/in" className="text-sm">
                    sign in
                  </Link>
                )}
              </div>
            </nav>
            <div className="border p-3">{children}</div>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
